# fly.toml app configuration file generated for discord-soundbot on 2023-10-31T23:02:00-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "discord-soundbot"
primary_region = "gru"

[build]
  dockerfile = "./Dockerfile"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source = "sounds"
  destination = "/app/sounds"